# WITH A AS (
#     SELECT DISTINCT CAR_ID 
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY    
#     WHERE START_DATE BETWEEN '2022-11-01' AND '2022-11-30' 
#              OR START_DATE < '2022-11-01' AND END_DATE >= '2022-11-01'
# )

# SELECT * FROM A

SELECT C.CAR_ID, C.CAR_TYPE, ROUND((DAILY_FEE*30)*((100-DISCOUNT_RATE)/100)) FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE AND DURATION_TYPE='30일 이상'
WHERE C.CAR_ID NOT IN (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY    
    WHERE START_DATE <= '2022-11-30' AND END_DATE>='2022-11-01'
    )          
     AND C.CAR_TYPE IN ('세단', 'SUV')
     AND ROUND(DAILY_FEE*30)*((100-DISCOUNT_RATE)/100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC