# 가입한 사람
# SELECT COUNT(*), DATE_FORMAT(JOINED, '%Y-%m') JD
# FROM USER_INFO
# GROUP BY JD;

# 구매한 사람
# SELECT COUNT(*), DATE_FORMAT(SALES_DATE, '%Y-%m') SD
# FROM ONLINE_SALE
# GROUP BY SD;

SELECT YEAR, MONTH, COUNT(*) PUCHASED_USERS, 
       ROUND(COUNT(*)/(SELECT COUNT(*)
                       FROM USER_INFO
                       WHERE YEAR(JOINED) = 2021),1) PUCHASED_RATIO 
FROM (SELECT DISTINCT YEAR(S.SALES_DATE) YEAR, MONTH(S.SALES_DATE) MONTH, U.USER_ID
      FROM ONLINE_SALE S
      JOIN USER_INFO U
      ON U.USER_ID = S.USER_ID AND YEAR(U.JOINED)=2021) A 
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
