SELECT E.ID, IFNULL(CHILD_COUNT,0) CHILD_COUNT
FROM ECOLI_DATA E
LEFT JOIN ( SELECT COUNT(*) AS CHILD_COUNT, PARENT_ID
            FROM ECOLI_DATA
            GROUP BY PARENT_ID) C
ON E.ID = C.PARENT_ID
ORDER BY E.ID