-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    UNION
    SELECT SALES_DATE, PRODUCT_ID, NULL USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    )
WHERE TO_CHAR(SALES_DATE, 'YYYYMMDD') BETWEEN '20220301' AND '20220331'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
