-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", B.BOARD_ID, "/", FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE F, USED_GOODS_BOARD B
WHERE F.BOARD_ID = (SELECT BOARD_ID
                   FROM USED_GOODS_BOARD
                   ORDER BY VIEWS DESC LIMIT 1)
                   AND F.BOARD_ID = B.BOARD_ID
ORDER BY FILE_ID DESC;