SELECT F.FLAVOR
FROM FIRST_HALF F, (SELECT SUM(TOTAL_ORDER) TOTAL_ORDER, FLAVOR
                    FROM JULY
                    GROUP BY FLAVOR) J
WHERE F.FLAVOR = J.FLAVOR
ORDER BY F.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3