SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) TOTAL_SALES 
FROM BOOK B, AUTHOR A, BOOK_SALES S
WHERE B.BOOK_ID = S.BOOK_ID AND B.AUTHOR_ID = A.AUTHOR_ID AND SALES_DATE >= '2022-01-01' AND SALES_DATE <= '2022-01-31'
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID, CATEGORY DESC;

# SELECT * FROM BOOK_SALES WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE <= '2022-01-31' GROUP BY BOOK_ID

# SELECT * FROM BOOK