SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM ( SELECT * 
        FROM APPOINTMENT
        WHERE DATE(APNT_YMD) = '2022-04-13'
        AND APNT_CNCL_YN = 'N'
        AND MCDP_CD = 'CS') A
INNER JOIN PATIENT P
ON P.PT_NO = A.PT_NO
INNER JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
ORDER BY APNT_YMD

# SELECT * 
# FROM APPOINTMENT
# WHERE DATE(APNT_YMD) = '2022-04-13'
# AND APNT_CNCL_YN = 'N'
# AND MCDP_CD = 'CS'
