# SELECT D.SKILL_CODE & SC.CODE = SC.CODE
# , D.SKILL_CODE & SC.CODE

# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS D
# WHERE D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
# OR D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
# ORDER BY ID

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
INNER JOIN (SELECT * FROM SKILLCODES WHERE NAME IN('C#', 'Python')) SC
ON D.SKILL_CODE & SC.CODE = SC.CODE
ORDER BY ID