SELECT A.CATEGORY, IFNULL(PRODUCTS, 0) PRODUCTS
FROM (SELECT DISTINCT LEFT(PRODUCT_CODE, 2) AS CATEGORY 
      FROM PRODUCT) A
LEFT JOIN (SELECT COUNT(*) AS PRODUCTS, LEFT(PRODUCT_CODE, 2) AS CATEGORY 
            FROM PRODUCT 
            GROUP BY LEFT(PRODUCT_CODE, 2)) B
ON A.CATEGORY = B.CATEGORY
ORDER BY CATEGORY