# SELECT ID, FISH_NAME, LENGTH
# FROM (SELECT ID, I.FISH_TYPE, I.LENGTH
#       FROM (SELECT FISH_TYPE, MAX(LENGTH) LENGTH
#             FROM FISH_INFO 
#             GROUP BY FISH_TYPE) A
#       JOIN FISH_INFO I
#       ON A.FISH_TYPE = I.FISH_TYPE AND A.LENGTH = I.LENGTH) B
# JOIN FISH_NAME_INFO N
# ON B.FISH_TYPE = N.FISH_TYPE
# ORDER BY ID
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE (I.FISH_TYPE, LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH)
                              FROM FISH_INFO
                              GROUP BY FISH_TYPE)
ORDER BY ID;
