SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(SUM(REVIEW_SCORE)/COUNT(*), 2) SCORE
FROM REST_INFO I, REST_REVIEW R
WHERE I.REST_ID = R.REST_ID AND SUBSTR(ADDRESS, 1, 2) = "서울"
GROUP BY I.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC

# SELECT * FROM REST_INFO